PharmaDemo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Brick__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brick</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Brick</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Organisations</relationshipLabel>
        <relationshipName>Bricks</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Call_Report__c.object
<CustomObject>
    <fields>
        <fullName>Brick__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brick</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Brick</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Report</relationshipLabel>
        <relationshipName>Call_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Call_Notes__c</fullName>
        <label>Call Notes</label>
        <picklist>
            <picklistValues>
                <fullName>Tolerability/Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comparative Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pathology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Efficacy</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Report</relationshipLabel>
        <relationshipName>R00Nj0000003oDKnEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Report</relationshipLabel>
        <relationshipName>R00Nj0000003oDKlEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Call_Objective__c</fullName>
        <label>Next Call Objective</label>
        <picklist>
            <picklistValues>
                <fullName>Discuss Efficacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provide Comparative Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tolerability/Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comparative Data</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telephone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eDetail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00Nj0000003oDLXEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call Report</label>
    <nameField>
        <label>Call Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Call_Notes__c</fullName>
        <label>Call Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Call_Objective__c</fullName>
        <label>Next Call Objective</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Brick</value>
            </filterItems>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>notEqual</operation>
                <value>TRUE</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brick__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brick</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Brick</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Medical Professionals</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Location</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>If( Account__r.Name = Contact__r.Account.Name ,&quot;Primary&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/classes/CallReport_Controller.cls
public class CallReport_Controller {

Call_Report__c call_report;
PageReference nextpage;


   public Call_Report__c getCall_Report() {
   string locationid = System.currentPageReference().getParameters().get('locationid');
   string contactid= System.currentPageReference().getParameters().get('contactid');
   string accountid = System.currentPageReference().getParameters().get('accountid');
   string UserId = userinfo.getUserId();
   
      if (call_report == null) call_report = new Call_Report__c();
        if (locationid == null)
        {
            call_report.location__c= accountid;
            call_report.contact__c= contactid;
        }
        else
        {
            location__c location = [select id, contact__c, account__c from location__c where id=:locationid];
            contactid = location.contact__c;
            accountid = location.account__c;
            call_report.contact__c = location.contact__c;
            call_report.location__c = location.account__c;
       }
        call_report.Type__c= System.currentPageReference().getParameters().get('type');
        contact contact = [select id, next_call_objective__c, call_notes__c from contact where id =:contactid];
        call_report.next_call_objective__c = contact.next_call_objective__c;
        call_report.call_notes__c = contact.call_notes__c;
        call_report.user__c = UserId;
        account account = [select id, brick__c from account where id =:accountid];
        call_report.brick__c = account.brick__c;
 
  
  return call_report;
   }
   
   
   public PageReference cancel() {
     nextpage = new PageReference('/'+call_report.contact__c);
     nextpage.setRedirect(true);
     return nextpage;
   }
   
   public PageReference save() {
     insert call_report;
     nextpage = new PageReference('/'+call_report.id);
     nextpage.setRedirect(true);
     return nextpage;
   }

}