PharmaDemo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AccountPlanogram__c</fullName>
        <label>AccountPlanogram</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Planogram__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Planogram Products</relationshipLabel>
        <relationshipName>Planograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Group_Image__c</fullName>
        <formula>IMAGE( Product__r.Grouped_Image__c ,  Product__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Group Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Planograms</relationshipLabel>
        <relationshipName>Planograms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space_Slot_Number__c</fullName>
        <description>Shelfs Top-&gt;Bottom A-&gt;D, Slots 1-&gt;4 Left-&gt;Right</description>
        <inlineHelpText>Shelfs Top-&gt;Bottom A-&gt;D, Slots 1-&gt;4 Left-&gt;Right</inlineHelpText>
        <label>Location on Shelf</label>
        <picklist>
            <picklistValues>
                <fullName>A1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Planogram</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Planogram Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planograms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Show_in_Planogram__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show in Planogram</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

PharmaDemo/src/classes/PlanogramTestClasses.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class PlanogramTestClasses {

    static testMethod void myUnitTest() {
        //Test The Account Planogram Trigger
        
        Product2 product = new Product2();
        product.Name = 'Test Product';
        product.Show_in_Planogram__c = true;
        insert product;
        
        
        
        Account a = new Account();
        a.Name = 'Test Class Debug Account';
        
        a.AccountPlanogram__c ='';
        
        for(Integer i = 0; i< 15; i++) {
        	a.AccountPlanogram__c += product.Id +',';		        	
        }
        a.AccountPlanogram__c += product.Id;
        insert a;
        
        Account fullAccount = [Select (Select Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastActivityDate, ConnectionReceivedId, ConnectionSentId, Account__c, Space_Slot_Number__c, Product__c, Index__c, Product_Group_Image__c From Planograms__r) From Account a where id =: a.Id];
        
        //there should be 16 planogram objects
        List<Planogram__c> planograms = fullAccount.Planograms__r;
        System.assertEquals(16, planograms.size());
                
        
        //Test The Planogram Ext
         Account acc = new Account();
        acc.Name = 'Test Class Debug Account';
        acc.AccountPlanogram__c ='';
          for(Integer i = 0; i< 15; i++) {
        	acc.AccountPlanogram__c += ',';		        	
        }
        acc.AccountPlanogram__c += '';
        insert acc;
                
        //Test The Planogram Ext
        ApexPages.StandardController std = new ApexPages.Standardcontroller(acc);
        PlanogramExt planogram = new PlanogramExt (std);
        acc.AccountPlanogram__c ='';
        
        for(Integer i = 0; i< 15; i++) {
        	acc.AccountPlanogram__c += product.Id +',';		        	
        }
        acc.AccountPlanogram__c += product.Id;
        
        planogram.customSave();
        
        fullAccount = [Select (Select Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastActivityDate, ConnectionReceivedId, ConnectionSentId, Account__c, Space_Slot_Number__c, Product__c, Index__c, Product_Group_Image__c From Planograms__r) From Account a where id =: acc.Id];
        
        //there should be 16 planogram objects
        planograms = fullAccount.Planograms__r;
        System.assertEquals(16, planograms.size());
        
        //Test the Planogram Setup Class
        List<Product2> products = [Select p.Show_in_Planogram__c, p.Name, p.Id From Product2 p where Show_in_Planogram__c = true];
        delete products;
        
        PlanogramSetup setup = new PlanogramSetup();
        setup.CreateProducts();
        
        products = [Select p.Show_in_Planogram__c, p.Name, p.Id From Product2 p where Show_in_Planogram__c = true];
        
        System.assertEquals(16, products.size());
        
        
        
    }
}