PharmaDemo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Actual_Calls__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Actual Calls</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Brick_Name__c</fullName>
        <formula>IF ( RecordTypeId = &quot;012j0000000bXwn&quot;, Name , IF( IsPersonAccount, Person_Account_Brick_Name__c, Brick__r.Name ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brick Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Calls__c</fullName>
        <formula>IF(ISPICKVAL(Target__c, &quot;High&quot;),24, 
IF(ISPICKVAL(Target__c, &quot;Medium&quot;),12, 
IF(ISPICKVAL(Target__c, &quot;Low&quot;),8, 0)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Target Calls</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <label>Target</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Target__c.object
<CustomObject>
    <label>Target</label>
    <nameField>
        <label>Target of</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PharmaDemo/src/classes/PlanogramAccountSelection.cls
public with sharing class PlanogramAccountSelection {

    public List<Account> allAccounts {get; set;}
    public String searchString {get; set;}
    public Integer resultsPerPage {get; set;}
    
    
    public PlanogramAccountSelection() {
        allAccounts = [select id, Name, BillingStreet, BillingCity, BillingState, Phone, Target__c, Brick_Name__c, Target_Calls__c, Actual_Calls__c from Account where RecordTypeId='012200000009bSCAAY' order by Name Asc];
        searchString = '';      
        resultsPerPage = 10;
        
        
    }
    
    public List<Account> getAccResults() {
        List<Account> results = new List<Account>();
        if(searchString == '') {
            for(Account a : allAccounts) {
                results.add(a);
                if(results.size() >= resultsPerPage) {
                    break;
                }
                
            }
        } else {
            for(Account a : allAccounts) {
                if(a.Name.toUpperCase().contains(searchString.toUpperCase())) {
                    results.add(a);
                    if(results.size() >= resultsPerPage) {
                        break;
                    }
                }                               
            }                               
        }
        return results;
    }
    
    
}