PharmaDemo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>Price_List__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Brick</value>
            </filterItems>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>notEqual</operation>
                <value>TRUE</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <formula>Contact__r.Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Location</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Price_List__c.object
<CustomObject>
    <label>Price List</label>
    <nameField>
        <label>Price List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Stock_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Stock Orders</relationshipLabel>
        <relationshipName>Stock_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Stock Orders</relationshipLabel>
        <relationshipName>Stock_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price List</label>
        <referenceTo>Price_List__c</referenceTo>
        <relationshipLabel>Stock Orders</relationshipLabel>
        <relationshipName>Stock_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wholesaler</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Stock Orders</relationshipLabel>
        <relationshipName>Stock_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stock Order</label>
    <nameField>
        <displayFormat>ORDER-{000000}</displayFormat>
        <label>Stock Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Wholesaler__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must choose an account/organisation</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Organisation</value>
            </filterItems>
            <infoMessage>Must choose an account/organisation</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wholesalers</relationshipLabel>
        <relationshipName>Wholesalers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wholesaler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wholesaler</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must choose an Wholesaler</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Wholesaler</value>
            </filterItems>
            <infoMessage>Must choose an Wholesaler</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Wholesalers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wholesaler</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Wholesaler</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wholesalers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/classes/NewStockOrder_Controller.cls
public class NewStockOrder_Controller {

Stock_Order__c stock_order;
PageReference nextpage;


   public Stock_order__c getStock_Order() {
   string accountid = System.currentPageReference().getParameters().get('accountid');
   string UserId = userinfo.getUserId();
    account account = [select id, price_list__c from account where id=:accountid];
   
      if (stock_order == null) stock_order = new Stock_Order__c();
        stock_order.OwnerId = UserId;
        stock_order.Account__c = accountid;
        stock_order.price_list__c = account.price_list__c;
 
  
  return stock_order;
   }
   
public List<selectOption> getWholesalers() {
           string accountid = System.currentPageReference().getParameters().get('accountid');
        List<selectOption> options = new List<selectOption>(); //new list for holding all of the picklist options
        options.add(new selectOption('', '- None -')); //add the first option of '- None -' in case the user doesn't want to select a value or in case no values are returned from query below
        for (Wholesaler__c wholesalers: [Select Wholesaler__c, Wholesaler__r.Name, Account__c, primary__c From Wholesaler__c Where Account__c = :accountID order by primary__c desc, Wholesaler__r.Name asc])
        {
            options.add(new selectOption(wholesalers.Wholesaler__c, wholesalers.Wholesaler__r.Name));
        }
        return options; //return the picklist options
        
    }  

public List<selectOption> getContacts() {
           string accountid = System.currentPageReference().getParameters().get('accountid');
        List<selectOption> contactoptions = new List<selectOption>(); //new list for holding all of the picklist options
        contactoptions.add(new selectOption('', '- None -')); //add the first option of '- None -' in case the user doesn't want to select a value or in case no values are returned from query below
        for (Location__c contacts: [Select contact__c, Contact_Name__c From Location__c Where Account__c = :accountID order by contact__r.LastName asc])
        {
            contactoptions.add(new selectOption(contacts.contact__c, contacts.Contact_Name__c));
        }
        return contactoptions ; //return the picklist options
        
    }       
   
   
   public PageReference cancel() {
     nextpage = new PageReference('/'+stock_order.account__c);
     nextpage.setRedirect(true);
     return nextpage;
   }
   
   public PageReference save() {
     insert stock_order;
     nextpage = new PageReference('/'+stock_order.id);
     nextpage.setRedirect(true);
     return nextpage;
   }
    

}