PharmaDemo/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Best_Time__c</fullName>
        <label>Best Time</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Call_Report__c.object
<CustomObject>
    <fields>
        <fullName>CallDate__c</fullName>
        <formula>Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CallDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Report</relationshipLabel>
        <relationshipName>R00Nj0000003oDKnEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW() + 7</defaultValue>
        <label>Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration (mins)</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Report</relationshipLabel>
        <relationshipName>R00Nj0000003oDKlEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telephone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eDetail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00Nj0000003oDLXEA2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call Report</label>
    <nameField>
        <label>Call Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Best_Time__c</fullName>
        <label>Best Time</label>
        <picklist>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>FirstName &amp; &quot; &quot; &amp;  LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Brick</value>
            </filterItems>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>notEqual</operation>
                <value>TRUE</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Best_Time__c</fullName>
        <label>Best Time</label>
        <picklist>
            <picklistValues>
                <fullName>Monday - AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday - PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday - AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday - PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday - AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday - PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday - AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday - PM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday - AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday - PM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Location</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>If( Account__r.Name = Contact__r.Account.Name ,&quot;Primary&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/classes/createMultipleCallRecords.cls
public class createMultipleCallRecords {

  ApexPages.StandardSetController con;
  string UserId = userinfo.getUserId();      
  public List<Call_Report__c> newCalls {get; set;}
  public List<Call_Report__c> calls {get;set;}
  public List<Location__c> selectedContacts {get; set;}
  
  //Constructor
    public createMultipleCallRecords(ApexPages.StandardSetController controller) {
      
      con = controller;
      
      if(this.con.getResultSize() > 0 ){ 
      this.con.setPageSize(5);
    } 
    //createCallReports();
    }
    
    //Create the Call Reports
    public void createCallReports() {

        //get the selected assets
        selectedContacts = (List<Location__c>)con.getSelected();
        List<ID> ContactIds = new List<ID> ();
        for (Location__c L : selectedContacts)
            ContactIds.add (L.id);
        selectedContacts = [select id, contact__c, account__c, best_time__c from Location__c where id in :ContactIds];
        
        //set up an empty list to hold the opportunities
        newCalls = new List<Call_Report__c>();
        
        
        
        for(Location__c c: selectedContacts){
              Date myDate = Date.today();
              Date weekStart = myDate.toStartofWeek();
              Integer hours = 0;
              date activityDate;

             if((c.Best_Time__c == '')||(c.Best_Time__c == null)){
                   activityDate = weekStart.addDays(7);
                   hours = 9;
              }else if(c.Best_Time__c == 'Monday - AM'){
                  activityDate = weekStart.addDays(7);
                  hours = 9;
              }else if(c.Best_Time__c == 'Monday - PM'){
                  activityDate = weekStart.addDays(7);
                  hours = 13;                  
              }else if(c.Best_Time__c == 'Tuesday - AM'){
                  activityDate = weekStart.addDays(8);
                  hours = 9;
              }else if(c.Best_Time__c == 'Tuesday - PM'){
                  activityDate = weekStart.addDays(7);
                  hours = 13;                                    
              }else if(c.Best_Time__c == 'Wednesday - AM'){
                  activityDate = weekStart.addDays(9);
                  hours = 9;
              }else if(c.Best_Time__c == 'Wednesday - PM'){
                  activityDate = weekStart.addDays(7);
                  hours = 13;                                    
              }else if(c.Best_Time__c == 'Thursday - AM'){
                  activityDate = weekStart.addDays(10);
                  hours = 9;                  
              }else if(c.Best_Time__c == 'Thursday - PM'){
                  activityDate = weekStart.addDays(7);
                  hours = 13;                                                     
              }else if(c.Best_Time__c == 'Friday - AM'){
                  activityDate = weekStart.addDays(11);
                  hours = 9;                  
              }else if(c.Best_Time__c == 'Friday- PM'){
                  activityDate = weekStart.addDays(7);
                  hours = 13;                                                     
              }
                  
             
              DateTime CallDate= datetime.newInstance(activityDate.year(), activityDate.month(), activityDate.day(), hours, 0, 0);             
          newCalls.add(new Call_Report__c(Contact__c = c.contact__c, location__c=c.account__c, Duration__c = '10', OwnerId=UserId, User__c=UserId, date__c = CallDate));
        }
        
        //insert into the db
        insert newCalls;
        pullRecords();
    }
    
    public PageReference pullRecords(){
      calls = new List<Call_Report__c>();
      List<Call_Report__c> temp  = [Select Type__c,Id, Location__c, Location__r.id, Location__r.Name, contact__c, contact__r.id, contact__r.Full_Name__c, Date__c, Calldate__c, User__c From Call_Report__c];
      
      for(Call_Report__c i: temp){
        for(Call_Report__c j: newCalls){
          if(i.Id == j.Id){
            calls.add(i);
          }
        }
      }
      
      return null;
    }

}