PharmaDemo/src/objects/Additional_Business_Plan_Contacts__c.object
<CustomObject>
    <fields>
        <fullName>Business_Plan__c</fullName>
        <label>Business Plan</label>
        <referenceTo>SFDC_Acct_Plan__c</referenceTo>
        <relationshipName>R00Nj0000003oDM8EAM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00Nj0000003oDM9EAM</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Stakeholder</label>
    <nameField>
        <label>Stakeholder</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stakeholders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Call_Indicator__c</fullName>
        <formula>IMAGE(&quot;http://chart.apis.google.com/chart?cht=gom&amp;chs=45x30&amp;chf=bg,s,FFFFFF&amp;chd=t:&quot; &amp; TEXT(pc_Target_Calls__c ),&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Call Indicator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KOL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>KOL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Activity__c</fullName>
        <label>Last Activity</label>
        <summarizedField>Call_Attendees__c.Call_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Call_Attendees__c.Type__c</field>
            <operation>equals</operation>
            <value>1:1, Meeting</value>
        </summaryFilterItems>
        <summaryForeignKey>Call_Attendees__c.Contact__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Spec__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specialty</label>
        <referenceTo>Speciality__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Brick</value>
            </filterItems>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>notEqual</operation>
                <value>TRUE</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Location</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Contact__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Activity__c</fullName>
        <formula>Contact__r.Last_Activity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Activity</label>
        <type>Date</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/SFDC_Acct_Plan__c.object
<CustomObject>
    <description>Overall goals, objectives, and challenges for penetrating an account.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contact&apos;s primary location must be same as Primary Account on Business Plan</errorMessage>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Organisation__c</valueField>
            </filterItems>
            <infoMessage>Contact&apos;s primary location must be same as Primary Account on Business Plan</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Business Plans</relationshipLabel>
        <relationshipName>R00Nj0000003oDM3EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organisation</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Business Plans</relationshipLabel>
        <relationshipName>R00Nj0000003oDLqEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Business Plan</label>
    <nameField>
        <label>Business Plan</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PharmaDemo/src/classes/BusinessPlanContactExtension.cls
public class BusinessPlanContactExtension {

    private SFDC_Acct_Plan__c gm;
    private String addContactIds = '';
    private String removeContactIds = '';

    
    private String singleContactId = '';
    
    private List <Location__c> accountContacts = new List<Location__c>();
    
    private List <Additional_Business_Plan_Contacts__c> attendees = new List<Additional_Business_Plan_Contacts__c>();

    public BusinessPlanContactExtension (ApexPages.StandardController controller) {
        this.gm = (SFDC_Acct_Plan__c)controller.getRecord();
        string accountid = System.currentPageReference().getParameters().get('accountid');
        gm.Organisation__c = accountid;
    }

    public List <Additional_Business_Plan_Contacts__c> getAttendees() {
        attendees = [Select Id, Contact__c, Contact__r.Email, Contact__r.Phone, Contact__r.Name, Contact__r.Call_Indicator__c, Contact__r.Spec__c, Contact__r.KOL__c from Additional_Business_Plan_Contacts__c Where Business_Plan__c = :gm.Id];
        return attendees;
    } 
    
    public List <Location__c> getAccountContacts() {
        string accountid = System.currentPageReference().getParameters().get('accountid');
        if (this.gm.Organisation__c != null) {
            accountContacts = [select id,  Email__c ,  contact__c, Contact__r.Name, Contact__r.Phone, Contact__r.Call_Indicator__c, Contact__r.Last_Activity__c, Contact__r.Spec__c,  Contact__r.KOL__c from location__c where Account__c =:accountid];
        }
        return accountContacts;
    } 
    
    public void setAddContactIds(String ids) {
        addContactIds = ids;     
    }

    public String getAddContactIds() {
        return addContactIds;     
    }

    public void setRemoveContactIds(String ids) {
        removeContactIds = ids;     
    }

    public String getRemoveContactIds() {
        return removeContactIds;     
    }

    public void setSingleContactId(String id) {
        singleContactId = id;     
    }

    public String getSingleContactId() {
        return singleContactId;     
    }

        
    public string goback() {
    string tt = '/'+System.currentPageReference().getParameters().get('id');
        return tt;

    }
    
    public void addSingleContact() {
        if(singleContactId != '') {
            Contact contact = [Select Id, Name From Contact Where Id = :singleContactId];
            if (contact != null) {           
                Additional_Business_Plan_Contacts__c gma = new Additional_Business_Plan_Contacts__c();
                gma.Contact__c = contact.Id;
                gma.Business_Plan__c = this.gm.Id;
                Database.SaveResult result = Database.Insert(gma, false);
            }
        }           
    }
    
   public void addContacts() {
        String[] ids = addContactIds.split(','); 
        if (ids.size() > 0) {
            List <Additional_Business_Plan_Contacts__c> attendeesToUpdate = new List <Additional_Business_Plan_Contacts__c>();        
            List<Contact> contacts = [Select Id, Name from Contact Where Id In : ids];
            for(Contact contact : contacts) {
                Boolean found = false;
                for (Additional_Business_Plan_Contacts__c attendee: attendees) {
                    if (attendee.Contact__c == contact.Id) {
                        found = true;
                    }
                }
                if ( ! found ) {
                    Additional_Business_Plan_Contacts__c gma = new Additional_Business_Plan_Contacts__c();
                    gma.Contact__c = contact.Id;
                    gma.Business_Plan__c = this.gm.Id;
                    attendeesToUpdate.add(gma);                 
                }
            }
            Database.SaveResult[] results = Database.Insert(attendeesToUpdate, false);
        }
    }
    
    public void removeContacts() {
        String[] ids = removeContactIds.split(',');
        List<String> deleteIds = new List<String>();
        for (String id : ids) {
            if (id.length() == 18) {
                deleteIds.add(id);  
            }   
        }
        if (deleteIds.size() > 0) {
            Database.DeleteResult[] results = Database.delete(deleteIds, false);
        } 
    }
    
 
}