PharmaDemo/src/objects/AppLauncher__c.object
<CustomObject>
    <description>Keeps records of all available mobile apps to be launched from the iPad/iPhone.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Projects</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <label>Icon</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Url__c</fullName>
        <label>Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>App Launcher</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App Launchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/classes/AppLauncherSetExtension.cls
public class AppLauncherSetExtension
{
  public ApexPages.StandardSetController setCon 
  {
    get 
    {
      if (setCon == null) {
        setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
          [
            Select Name, Icon__c, Category__c, Url__c
            From AppLauncher__c
            Order by Name
          ]
        ));
      }
      return setCon;
    }
    set;
  }
  public String cat { get; set; }
  
  public Map<String, List<AppLauncher__c>> getApps()
  {
    Map<String, List<AppLauncher__c>> itemMap = new Map<String, List<AppLauncher__c>>();
    for (AppLauncher__c item : (List<AppLauncher__c>)setCon.getRecords()) {
      if (cat == 'All' || cat == item.Category__c) {
        if (item.Category__c == null) item.Category__c = 'None';
        if (!itemMap.containsKey(item.Category__c))
          itemMap.put(item.Category__c, new List<AppLauncher__c>());
        itemMap.get(item.Category__c).add(item);
      }
    }
    return itemMap;
  }
  
  public AppLauncherSetExtension(ApexPages.StandardSetController c)
  {
    cat = ApexPages.currentPage().getParameters().get('category');
    if (cat == null) cat = 'HR';
  }
}