PharmaDemo/src/objects/AppLauncher__c.object
<CustomObject>
    <description>Keeps records of all available mobile apps to be launched from the iPad/iPhone.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Projects</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>App Launcher</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App Launchers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/classes/TestAppLauncher.cls
@isTest
private class TestAppLauncher {
	
	public static testmethod void testAppL() {
		
		AppLauncher__c al1 = new AppLauncher__c();
		al1.Category__c = 'HR';
		al1.Name = 'app1';
		
		insert al1;
		
		ApexPages.Standardsetcontroller con = new ApexPages.Standardsetcontroller([select Id, Name from AppLauncher__c limit 20]);
		AppLauncherSetExtension ase = new AppLauncherSetExtension(con);
		
		System.assertNotEquals(ase.getApps(), null);
		
	}
	
}