PharmaDemo/src/objects/Call_Attendees__c.object
<CustomObject>
    <fields>
        <fullName>Call_Date__c</fullName>
        <label>Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <label>Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Call_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Report</relationshipLabel>
        <relationshipName>R00Nj0000003oDLLEA2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Face to Face</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Attendee</label>
    <nameField>
        <label>Call Attendee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Call_Report__c.object
<CustomObject>
    <fields>
        <fullName>CallDate__c</fullName>
        <formula>Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CallDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Report</relationshipLabel>
        <relationshipName>R00Nj0000003oDKnEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Report</relationshipLabel>
        <relationshipName>R00Nj0000003oDKlEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telephone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eDetail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Report</label>
    <nameField>
        <label>Call Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Call_Indicator__c</fullName>
        <formula>IMAGE(&quot;http://chart.apis.google.com/chart?cht=gom&amp;chs=45x30&amp;chf=bg,s,FFFFFF&amp;chd=t:&quot; &amp; TEXT(pc_Target_Calls__c ),&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Call Indicator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KOL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>KOL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Activity__c</fullName>
        <label>Last Activity</label>
        <summarizedField>Call_Attendees__c.Call_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Call_Attendees__c.Type__c</field>
            <operation>equals</operation>
            <value>1:1, Meeting</value>
        </summaryFilterItems>
        <summaryForeignKey>Call_Attendees__c.Contact__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Spec__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Specialty</label>
        <referenceTo>Speciality__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Brick</value>
            </filterItems>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>notEqual</operation>
                <value>TRUE</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Location</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>Contact__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Activity__c</fullName>
        <formula>Contact__r.Last_Activity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Activity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>If( Account__r.Name = Contact__r.Account.Name ,&quot;Primary&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/PharmaProduct__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Detail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Product_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Call_Indicator__c</fullName>
        <formula>IMAGE(&quot;http://chart.apis.google.com/chart?cht=gom&amp;chs=45x30&amp;chf=bg,s,FFFFFF&amp;chd=t:&quot; &amp; TEXT( Call_Report__r.Contact__r.pc_Target_Calls__c ),&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Call Indicator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <label>Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Product Detail</relationshipLabel>
        <relationshipName>Product_Detail</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>PharmaProduct__c</referenceTo>
        <relationshipLabel>Product Detail</relationshipLabel>
        <relationshipName>R00Nj0000003oDL5EAM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Detail</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Product Detail</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Promotional_Item__c.object
<CustomObject>
    <fields>
        <fullName>Call_Report__c</fullName>
        <label>Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Promotional Items</relationshipLabel>
        <relationshipName>Promotional_Item</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Promotional Items</relationshipLabel>
        <relationshipName>Promotional_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Promotional_Product__c</fullName>
        <label>Promotional Product</label>
        <referenceTo>Promotional_Product__c</referenceTo>
        <relationshipLabel>Promotional Items</relationshipLabel>
        <relationshipName>R00Nj0000003oDKzEAM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Promotional Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Promotional Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotional Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Promotional_Product__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Promotional Product</label>
    <nameField>
        <label>Promotional Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotional Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Sample__c.object
<CustomObject>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sample</label>
    <nameField>
        <label>Sample Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Sample_Item__c.object
<CustomObject>
    <fields>
        <fullName>Call_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Sample Items</relationshipLabel>
        <relationshipName>Sample_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sample Items</relationshipLabel>
        <relationshipName>Sample_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sample__c</fullName>
        <label>Sample</label>
        <referenceTo>Sample__c</referenceTo>
        <relationshipLabel>Sample Items</relationshipLabel>
        <relationshipName>R00Nj0000003oDL0EAM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sample Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Sample Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/classes/GroupMeetingAttendeeExtension.cls
public class GroupMeetingAttendeeExtension {
    public PharmaProduct__c[] plans {get;set;}
    public ProdSect[] selection {get; set;}
    public Sample__c[] samplenames {get;set;}
    public SampleSect[] samp {get;set;}
    public Promotional_Product__c[] promonames {get;set;}
    public PromoSect[] promo {get;set;}


    private Call_Report__c gm;
    private String addContactIds = '';
    private String removeContactIds = '';

    
    private String singleContactId = '';
    
    private List <Location__c> accountContacts = new List<Location__c>();
    
    private List <Call_Attendees__c> attendees = new List<Call_Attendees__c>();

    public GroupMeetingAttendeeExtension (ApexPages.StandardController controller) {
        this.gm = (Call_Report__c)controller.getRecord();
        
        
        
        selection = new ProdSect[]{};
        plans = [select Name
             from PharmaProduct__c ];
        
        for (PharmaProduct__c p : plans){
            
            
                    selection.add(new ProdSect(new Product_Detail__c(),p,false));
                    
    
        }
        
        
        
        
        
        samp = new SampleSect[]{};  
        samplenames = [select Name, Cost__C
                    from Sample__c];                
        for (Sample__c s : samplenames){
            
                    samp.add(new SampleSect(new Sample_Item__c(),s,false));
                    
        
        }
        
        promo = new PromoSect[]{};
        promonames=[select Name, Cost__c
                    from Promotional_Product__c];
        for (Promotional_Product__c pr : promonames){
        
                 promo.add(new PromoSect(new Promotional_Item__c(), pr, false));
            
        }
        
        
        
        
        
    }

    public List <Call_Attendees__c> getAttendees() {
        attendees = [Select Id, Contact__c, Contact__r.Email, Contact__r.Phone, Contact__r.Name, Contact__r.Call_Indicator__c,  Contact__r.Spec__c, Contact__r.KOL__c from Call_Attendees__c Where Call_Report__c = :gm.Id];
        return attendees;
    } 
    
    public List <Location__c> getAccountContacts() {
    
        if (this.gm.Location__c != null) {
            accountContacts = [select id,  Email__c ,  contact__c, Contact__r.Name, Contact__r.Phone, Contact__r.Call_Indicator__c, Contact__r.Last_Activity__c, Contact__r.Spec__c, Contact__r.KOL__c from location__c where Account__c =:this.gm.Location__c];
        }
        return accountContacts;
    } 
    
    public void setAddContactIds(String ids) {
        addContactIds = ids;     
    }

    public String getAddContactIds() {
        return addContactIds;     
    }

    public void setRemoveContactIds(String ids) {
        removeContactIds = ids;     
    }

    public String getRemoveContactIds() {
        return removeContactIds;     
    }

    public void setSingleContactId(String id) {
        singleContactId = id;     
    }

    public String getSingleContactId() {
        return singleContactId;     
    }

        
    public string goback() {
    string tt = '/'+System.currentPageReference().getParameters().get('id');
        return tt;

    }
    
    public void addSingleContact() {
        if(singleContactId != '') {
            Contact contact = [Select Id, Name From Contact Where Id = :singleContactId];
            if (contact != null) {           
                Call_Attendees__c gma = new Call_Attendees__c();
                gma.Contact__c = contact.Id;
                    Call_Report__c c2 = [select id,calldate__c, Type__c from Call_report__c where id=:this.gm.Id];        
                    gma.Type__c = c2.Type__c;                         
                    gma.Call_Date__c = c2.CallDate__c;
                    gma.Name = contact.Name;                         
                gma.Call_Report__c = this.gm.Id;
                Database.SaveResult result = Database.Insert(gma, false);
            }
        }           
    }
    
   public void addContacts() {
        String[] ids = addContactIds.split(','); 
        if (ids.size() > 0) {
            List <Call_Attendees__c> attendeesToUpdate = new List <Call_Attendees__c>();        
            List<Contact> contacts = [Select Id, Name from Contact Where Id In : ids];
            for(Contact contact : contacts) {
                Boolean found = false;
                for (Call_Attendees__c attendee: attendees) {
                    if (attendee.Contact__c == contact.Id) {
                        found = true;
                    }
                }
                if ( ! found ) {
                    Call_Attendees__c gma = new Call_Attendees__c();
                    gma.Contact__c = contact.Id;
                    Call_Report__c c2 = [select id,calldate__c, Type__c from Call_report__c where id=:this.gm.Id];        
                    gma.Type__c = c2.Type__c;                         
                    gma.Call_Date__c = c2.CallDate__c;                         
                    gma.Call_Report__c = this.gm.Id;
                    gma.Name = contact.Name;
                    attendeesToUpdate.add(gma);                 
                }
            }
            Database.SaveResult[] results = Database.Insert(attendeesToUpdate, false);
        }
    }
    
    public void removeContacts() {
        String[] ids = removeContactIds.split(',');
        List<String> deleteIds = new List<String>();
        for (String id : ids) {
            if (id.length() == 18) {
                deleteIds.add(id);  
            }   
        }
        if (deleteIds.size() > 0) {
            Database.DeleteResult[] results = Database.delete(deleteIds, false);
        } 
    }
    
    
    
    
    
    public pageReference save(){
        
    Product_Detail__c[] newPD = new Product_Detail__c[]{};
    Sample_Item__c[] newSI = new Sample_Item__c[]{};
    Promotional_Item__c[] newPI = new Promotional_Item__c[]{};
    
     String url = '/' + gm.Id;
     
     for (ProdSect PS: selection){
        
//        if(PS.selected == true){
        if(PS.prodD.Sequence__c > 0){
            PS.prodD.Name = PS.Product.Name;  
            PS.prodD.Product__c = PS.Product.Id;
            PS.prodD.Call_Report__c = gm.ID;
            newPD.add(PS.ProdD);

        }
     }
     
     insert newPD;
     
      for (SampleSect PS: samp){
        
//        if(PS.selected == true){
        if(PS.SI.Quantity__c >0){   
            PS.SI.Name = PS.Sample.Name;   
            PS.SI.Sample__c = PS.Sample.Id;
            PS.SI.Call_Report__c = gm.ID;
            PS.SI.Contact__c = gm.Contact__c;
            PS.SI.Cost__c = PS.Sample.Cost__c;
            newSI.add(PS.SI);

        }
     }
     
     insert newSI;
     
      for (PromoSect PS: promo){
//        if(PS.selected == true){
        if(PS.PI.Qty__c > 0){
            PS.PI.Name = PS.promoprod.Name;           
            PS.PI.Promotional_Product__c = PS.promoprod.Id;
            PS.PI.Call_Report__c = gm.ID;
            PS.PI.Contact__c = gm.Contact__c;   
            PS.PI.Cost__c = PS.promoprod.Cost__c;
            newPI.add(PS.PI);
        }
     }
     
     insert newPI;
     
    
    pageReference pr = new pageReference(url); 
    pr.setRedirect(true);
    return pr;
        
    //return null;  
        
        
        
    }
    
    
    
    
    
    public class ProdSect{
        
        
        public boolean selected {get; set;}
        public Product_Detail__c prodD {get; set;}
        public PharmaProduct__c product {get;set;}
        
        
        
        public ProdSect(Product_Detail__c p, PharmaProduct__c item, boolean checkbox){
            prodD = p;
            product = item;
            checkbox = selected;
            
                
        }
        
    }
    
    
    
    
    
    public class SampleSect{
        
        
        public boolean selected {get; set;}
        public Sample_Item__c SI {get; set;}
        public Sample__c sample {get;set;}
        
        
        
        public SampleSect(Sample_Item__c p, Sample__c item, boolean checkbox){
            SI = p;
            sample = item;
            checkbox = selected;
            
                
        }   
    }
    
    
     public class PromoSect{
        
        
        public boolean selected {get; set;}
        public Promotional_Item__c PI {get; set;}
        public Promotional_Product__c promoprod {get;set;}
        
        
        
        public PromoSect(Promotional_Item__c p, Promotional_Product__c item, boolean checkbox){
            PI = p;
            promoprod = item;
            checkbox = selected;
            
                
        }   
    }
}