PharmaDemo/src/objects/Call_Attendees__c.object
<CustomObject>
    <fields>
        <fullName>Call_Report__c</fullName>
        <label>Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Call_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Call Attendee</label>
    <nameField>
        <label>Call Attendee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Call_Report__c.object
<CustomObject>
    <fields>
        <fullName>Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <label>Call Report</label>
    <nameField>
        <label>Call Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PharmaDemo/src/classes/DispatcherCallAttendeeEditController.cls
public class DispatcherCallAttendeeEditController{
 
    public DispatcherCallAttendeeEditController(ApexPages.StandardController controller) {
        this.controller = controller;
    }
 
    public PageReference getRedir() {
        Call_Attendees__c att = [select id, Call_Report__c from Call_Attendees__c where id = :ApexPages.currentPage().getParameters().get('id')];     
        Call_Report__c c = [Select id, closed__c From call_report__c Where Id =: att.Call_Report__c];
 
        PageReference newPage;
 
        if (c.closed__c) {
            newPage = Page.NoEdit;
        } else {
            newPage = new PageReference('/' + att.id);
            newPage.getParameters().put('nooverride', '1');
        }
 
        newPage.getParameters().put('id', att.id);
        return newPage.setRedirect(true);
 
    }
 
    private final ApexPages.StandardController controller;
 
}