PharmaDemo/src/objects/Call_Report__c.object
<CustomObject>
    <label>Call Report</label>
    <nameField>
        <label>Call Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PharmaDemo/src/objects/TF__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Target Frequency</label>
    <nameField>
        <displayFormat>TF-{0000000}</displayFormat>
        <label>TF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Frequency</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/classes/SubmitTF.cls
public class SubmitTF{

    public SubmitTF(ApexPages.StandardController controller) {

    }


  ApexPages.StandardSetController con;
  string UserId = userinfo.getUserId();      
  public List<Call_Report__c> TFs {get;set;}
  public List<TF__c> selectedTFs {get; set;}
  
  //Constructor
    public SubmitTF(ApexPages.StandardSetController controller) {
      
      con = controller;
      
      if(this.con.getResultSize() > 0 ){ 
      this.con.setPageSize(5);
    } 

    }
    
    public void SubmitTFs() {

        //get the selected assets
        selectedTFs = (List<TF__c>)con.getSelected();
        List<ID> TFIds = new List<ID> ();
        for (TF__c T : selectedTFs)
            TFIds.add (T.id);
        selectedTFs = [select id, Status__c from TF__c where id in :TFIds];
        
        
        for(TF__c TF: selectedTFs){
              string status = 'Submitted';
              TF.status__c = status;
        }
        

    }
    


}