PharmaDemo/src/objects/Call_Attendees__c.object
<CustomObject>
    <fields>
        <fullName>Call_Date__c</fullName>
        <label>Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Call_Report__c</fullName>
        <label>Call Report</label>
        <referenceTo>Call_Report__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Call_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Report</relationshipLabel>
        <relationshipName>R00Nj0000003oDLLEA2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Face to Face</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Attendee</label>
    <nameField>
        <label>Call Attendee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Call_Report__c.object
<CustomObject>
    <fields>
        <fullName>CallDate__c</fullName>
        <formula>Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CallDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Report</relationshipLabel>
        <relationshipName>R00Nj0000003oDKnEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>NOW() + 7</defaultValue>
        <label>Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call Report</relationshipLabel>
        <relationshipName>R00Nj0000003oDKlEAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1:1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mailing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telephone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>eDetail</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Call Report</label>
    <nameField>
        <label>Call Report</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Brick</value>
            </filterItems>
            <filterItems>
                <field>Account.IsPersonAccount</field>
                <operation>notEqual</operation>
                <value>TRUE</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <formula>Contact__r.Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Location</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <formula>If( Account__r.Name = Contact__r.Account.Name ,&quot;Primary&quot;,&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/classes/CallReportAddContacts.cls
public class CallReportAddContacts {






    Account acc;
    Call_Report__c crc;
    String loc;
    String newContact;
    Call_Attendees__c newAttendee;
    
    public Account getAccount() {
       Call_Report__c crc = [Select c.Name, c.Location__r.Name, c.Location__r.Id, c.Location__c, c.Id From Call_Report__c c where c.id = :System.currentPageReference().getParameters().get('id')];
       Account acc = [Select a.Name, a.Id From Account a where a.id =: crc.Location__r.Id];
       return acc;

        
    }
       public Call_Report__c getCallReport() {
       Call_Report__c crc = [Select c.Name, c.Location__r.Name, date__c,c.Location__r.Id, c.Location__c, c.Id From Call_Report__c c where c.id = :System.currentPageReference().getParameters().get('id')];
       return crc;

        
    }
    public list<Location__c> getContacter(){
        Call_Report__c crc = [Select c.Name, c.Location__r.Name, c.Location__r.Id, c.Location__c, c.Id From Call_Report__c c where c.id = :System.currentPageReference().getParameters().get('id')];

        return [Select Contact__c, Contact_Name__c From Location__c where Account__c =:crc.Location__r.id];

    }
    public list<Call_Attendees__c> getselectedContacts(){
        
        return [Select c.Id, c.Contact__r.Name, c.Contact__c, c.Call_Report__c From Call_Attendees__c c where c.Call_Report__c=:System.currentPageReference().getParameters().get('id')];
    }
    public PageReference addContactToCallReport(){
       //Call_Attendees__c newAttendee2;
      //      newContact=System.currentPageReference().getParameters().get('contactid');
     //    newAttendee2.Contact__c =newContact;
     //   newAttendee2.Call_Report__c=System.currentPageReference().getParameters().get('id');
    //    insert newAttendee2;
        return null;
    }
    
    public string delContact() {
        Call_Attendees__c delattendee = [select id from Call_Attendees__c where id=:System.currentPageReference().getParameters().get('attid')];
        delete delattendee;
        return null;
    }
    public string testparam(){
        newContact =System.currentPageReference().getParameters().get('contactid');
        Call_Attendees__c newAttendee2 = new Call_Attendees__c();
        newAttendee2.Contact__c=newContact;
        Call_Report__c c2 = [select id,calldate__c, Type__c from Call_report__c where id=:System.currentPageReference().getParameters().get('id')];
        newAttendee2.Call_Date__c = c2.callDate__c;
        newAttendee2.Type__c = c2.Type__c;        
        newAttendee2.Call_Report__c = c2.id;
        //newAttendee2.Call_Report__c=System.currentPageReference().getParameters().get('id');
        insert newAttendee2;
        return null;
    }
    public string getContactSelected(){
        return newContact ;
    }
    public string goback() {
    string tt = '/'+System.currentPageReference().getParameters().get('id');
        return tt;

    }
}