PharmaDemo/src/objects/Campaign.object
<CustomObject>
    <recordTypes>
        <fullName>Campaign</fullName>
        <active>true</active>
        <description>Marketing Campaign</description>
        <label>Campaign</label>
    </recordTypes>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Sample__c.object
<CustomObject>
    <label>Sample</label>
    <nameField>
        <label>Sample Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Samples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Sample_Item__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sample Items</relationshipLabel>
        <relationshipName>Sample_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sample__c</fullName>
        <label>Sample</label>
        <referenceTo>Sample__c</referenceTo>
        <relationshipLabel>Sample Items</relationshipLabel>
        <relationshipName>R00Nj0000003oDL0EAM</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sample Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Sample Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/classes/ContactSamples.cls
public class ContactSamples { 

    private final Contact contact; 

    public ContactSamples (ApexPages.StandardController stdController) { 
        this.contact = (Contact)stdController.getRecord();      
    }                                

    public String getChartData() { 
        // The list of chart items 

        List<ChartDataItem> items = new List<ChartDataItem>(); 

        // List of valid Campaign Member Statuses for the Campaign 

        List<Sample__c> list_sample = [select Id, name from Sample__c]; 

        // Loop through each Sample, get a count of Samples left and add to list

        for (Sample__c smpl: list_sample) { 

            integer Count = [select count() from Sample_Item__c where Contact__c = :this.contact.Id AND Sample__c = : smpl.Id]; 

            if (Count > 0) { 
                items.add(new ChartDataItem(smpl.Name, Count.format())); 
            } 
        } 


        // Initialize Strings 

        String chd = ''; // Data 
        String chl = ''; // Labels 
        String chdl = ''; // Key 

        for(ChartDataItem citem : items) { 
            chd += citem.ItemValue + ','; 
            chdl += citem.Label + ' (' + citem.ItemValue + ')|'; 
            chl += citem.ItemValue + '|'; 
        } 

        //remove the last comma or pipe 
        if (items.size() > 0) { 
            chd = chd.substring(0, chd.length() -1); 
            chdl = chdl.substring(0, chdl.length() -1); 
            chl = chl.substring(0, chl.length() -1);             
        } 

 

        // We are only returning the values and labels. The rest of the URL string is in the VF page 
        String result = '&chd=t:' + chd + '&chdl=' + chdl + '&chl=' + chl; // &chl returns with labels pointing to pie pieces 
        //String result = '&chd=t:' + chd + '&chdl=' + chl; // &chdl returns with labels in a legend 

        return result; 
    } 


    // Class holding each chart data item 
    public class ChartDataItem { 

        public String ItemValue {get; set;} 

        public String Label {get; set;} 

        public ChartDataItem(String Label, String Value) 
        { 
            this.Label = Label; 
            this.ItemValue = Value; 
        } 
    } 

}