PharmaDemo/src/objects/Leave_Balance__c.object
<CustomObject>
    <fields>
        <fullName>BalanceEntitlementQuantity__c</fullName>
        <label>BalanceEntitlementQuantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DeductionEndDate__c</fullName>
        <label>DeductionEndDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DeductionStartDate__c</fullName>
        <label>DeductionStartDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TimeAccountTypeName__c</fullName>
        <label>TimeAccountTypeName</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeAccountType__c</fullName>
        <label>TimeAccountType</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leave_Balances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Leave Balance</label>
    <nameField>
        <displayFormat>LB-{0000}</displayFormat>
        <label>Leave Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>SAP_EmployeeID__c</fullName>
        <label>SAP EmployeeID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

PharmaDemo/src/classes/LeaveBalanceSetExtension.cls
public class LeaveBalanceSetExtension
{

  public List<Leave_Balance__c> balances {get;set;}  
   
  public LeaveBalanceSetExtension()
  {
      balances = [
            SELECT BalanceEntitlementQuantity__c,DeductionEndDate__c,DeductionStartDate__c,Id,TimeAccountTypeName__c,TimeAccountType__c
            FROM Leave_Balance__c            
            Where User__c = :UserInfo.getUserId()
          ];
  }  

    
  //DVP : Method that calls Cast Iron / SAP to get the latest Leave Requests and Balances for the current user
  
    public void calloutIbmci() {
		/**
        String empid = [select Id, SAP_EmployeeID__c from User where Id =:UserInfo.getUserId()].SAP_EmployeeID__c;
        String endpointUrl = 'https://castironpoc.w2k.nestle.net/userStatusAndInfo';
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setEndpoint(endpointUrl+'?EmployeeID='+empid+'&sfid='+UserInfo.getUserId());
        
        //send the request
        Http http = new Http();
        HttpResponse res = http.send(req);
        
        String httpresult = res.getBody();

        if (res.getStatus() == 'Success') {
            System.debug('******** IBM HTTP LR Test ****** :'+res.getBody());
        } else {
            System.debug('Callout failed: ' + res);
        } 
        **/
    }

}