PharmaDemo/src/objects/Leave_Balance__c.object
<CustomObject>
    <fields>
        <fullName>BalanceApprovedQuantity__c</fullName>
        <label>BalanceApprovedQuantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BalanceAvailableQuantity__c</fullName>
        <label>BalanceAvailableQuantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BalanceEntitlementQuantity__c</fullName>
        <label>BalanceEntitlementQuantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BalancePlannedQuantity__c</fullName>
        <label>BalancePlannedQuantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BalanceRequestedQuantity__c</fullName>
        <label>BalanceRequestedQuantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BalanceUsedQuantity__c</fullName>
        <label>BalanceUsedQuantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TimeAccountTypeName__c</fullName>
        <label>TimeAccountTypeName</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TimeAccountType__c</fullName>
        <label>TimeAccountType</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leave_Balances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Leave Balance</label>
    <nameField>
        <displayFormat>LB-{0000}</displayFormat>
        <label>Leave Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Leave_Request__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>Date</type>
    </fields>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{DD}-{MM}-{YYYY}-{000}</displayFormat>
        <label>Leave Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/classes/TestLeaveRequests.cls
@isTest
private class TestLeaveRequests {


	//test leave balance set extension
	private static testMethod void testLeaveBalanceSetExtension() {
		//set up a leave balance
		Leave_Balance__c lb = new Leave_Balance__c();
		lb.BalanceApprovedQuantity__c = 10;
		lb.BalanceAvailableQuantity__c = 20;
		lb.BalanceEntitlementQuantity__c = 30;
		lb.BalancePlannedQuantity__c = 5;
		lb.BalanceRequestedQuantity__c = 5;
		lb.BalanceUsedQuantity__c = 15;
		lb.TimeAccountType__c = '01';
		lb.TimeAccountTypeName__c = 'Vacation';
		lb.User__c = Userinfo.getUserId();
		insert lb;
				
		LeaveBalanceSetExtension lbse = new LeaveBalanceSetExtension();
		System.assertNotEquals(lbse.balances , null);
	}
	
	//test leave request detail controller
	private static testmethod void testleaverequestdetailcontroller() {		
		System.assertEquals(LeaveRequestDetailController.saveLeaveRequest(null, 'Vacation', Date.today(), Date.today().addDays(1), 'notes'), 'Saved');
	}
	
	//test leave request extension
	private static testmethod void testleaverequestextension() {
		Leave_Request__c lr = new Leave_Request__c();
		lr.From__c = Date.today();
		lr.To__c = Date.today().addDays(1);
		lr.Approval_Status__c = 'pending';
		
		insert lr;
		
		ApexPages.Standardcontroller con = new ApexPages.Standardcontroller(lr);
		LeaveRequestExtension lre = new LeaveRequestExtension(con);
		//just run some methods
		lre.getFormattedFrom();
		lre.getFormattedTo();
		lre.save();
		lre.cancel();
		
		//create a new one - no id
		Leave_Request__c lr2 = new Leave_Request__c();
		lr2.From__c = Date.today();
		lr2.To__c = Date.today().addDays(1);
		lr2.Approval_Status__c = 'pending';
		
		ApexPages.Standardcontroller con2 = new ApexPages.Standardcontroller(lr2);
		LeaveRequestExtension lre2 = new LeaveRequestExtension(con2);
		lre2.save();
		lre2.cancel();
		
	}
	
	//test leave requestsetextension
	private static testmethod void testleaverequestsetextension() {
		Leave_Request__c lr = new Leave_Request__c();
		lr.From__c = Date.today();
		lr.To__c = Date.today().addDays(1);
		lr.Approval_Status__c = 'pending';
		
		insert lr;
		
		ApexPages.Standardsetcontroller con = new ApexPages.Standardsetcontroller([select Id, Name from Leave_Request__c limit 10]);
		LeaveRequestSetExtension lrse = new LeaveRequestSetExtension(con);
		System.assertNotEquals(lrse.getRequests(), null);
		
	} 

	//empty method test
	private static testMethod void testJsonController() {
		costcenter_json_controller cjc = new costcenter_json_controller();
		cjc.getCostcenters();
	}

}