PharmaDemo/src/objects/Leave_Balance__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leave_Balances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Leave Balance</label>
    <nameField>
        <displayFormat>LB-{0000}</displayFormat>
        <label>Leave Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Leave_Request__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Approver Leave Requests</relationshipLabel>
        <relationshipName>Approver_Leave_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Leave_Type__c</fullName>
        <label>Leave Type</label>
        <picklist>
            <picklistValues>
                <fullName>Vacation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Work Accident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sick Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpaid Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sick Leave (average)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Short_Title__c</fullName>
        <description>Formula field summarizing the request. Useful for mobile display</description>
        <formula>TEXT(DAY(From__c)) &amp; &quot; &quot; &amp;
CASE( MONTH(From__c),
  1, &quot;Jan&quot;,
  2, &quot;Feb&quot;,
  3, &quot;Mar&quot;,
  4, &quot;Apr&quot;,
  5, &quot;May&quot;,
  6, &quot;Jun&quot;,
  7, &quot;Jul&quot;,
  8, &quot;Aug&quot;,
  9, &quot;Sep&quot;,
 10, &quot;Oct&quot;,
 11, &quot;Nov&quot;,
 12, &quot;Dec&quot;,
&quot;—&quot;) &amp; &quot; &quot; &amp;
TEXT(YEAR(From__c))

&amp; &apos; : &apos; 

&amp; TEXT(Leave_Type__c)</formula>
        <label>Short Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>Date</type>
    </fields>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{DD}-{MM}-{YYYY}-{000}</displayFormat>
        <label>Leave Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>SAP_EmployeeID__c</fullName>
        <label>SAP EmployeeID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

PharmaDemo/src/classes/LeaveRequestSetExtension.cls
public class LeaveRequestSetExtension
{
    
    public String castironurl {get;set;}

  public ApexPages.StandardSetController setCon 
  {
  	get 
  	{
  		if (setCon == null) {
  			setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
          [
            Select Name, Owner.Name, Approval_Status__c, Approver__c, Approver__r.Name, Approver__r.SmallPhotoUrl, From__c, Leave_Type__c, Notes__c, Short_Title__c, To__c
            From Leave_Request__c
            Where OwnerId = :UserInfo.getUserId() order by From__c desc
          ]
  			));
  		}
  		return setCon;
  	}
  	set;
  }
  public String status { get; set; }
  
  public Map<String, List<Leave_Request__c>> getRequests()
  {
  	Map<String, List<Leave_Request__c>> l = new Map<String, List<Leave_Request__c>>();
  	for (Leave_Request__c lr : (List<Leave_Request__c>)setCon.getRecords()) {
  		if (status == 'All' || status == lr.Approval_Status__c) {
  			if (lr.Approval_Status__c == null) lr.Approval_Status__c = 'None';
	  		if (!l.containsKey(lr.Approval_Status__c))
	  		  l.put(lr.Approval_Status__c, new List<Leave_Request__c>());
	  		l.get(lr.Approval_Status__c).add(lr);
  		}
  	}
  	return l;
  }

  public LeaveRequestSetExtension(ApexPages.StandardSetController c)
  {
    status = ApexPages.currentPage().getParameters().get('status');
    if (status == null) status = 'Pending';
    
    //just provide the UI with the CI url, it can do the callout itself
    //String empid = [select Id, SAP_EmployeeID__c from User where Id =:UserInfo.getUserId()].SAP_EmployeeID__c;
    //String endpointUrl = 'https://castironpoc.w2k.nestle.net/userStatusAndInfo';
    //castironurl =  endpointUrl+'?EmployeeID='+empid+'&sfid='+UserInfo.getUserId();
  }
    
  //DVP : Method that calls Cast Iron / SAP to get the latest Leave Requests and Balances for the current user
  
    public void calloutIbmci() {
		/**
        //get the current leave balances, we'll delete those after the callout
        //List<Leave_Balance__c> bls = [select Id from Leave_Balance__c where User__c =:UserInfo.getUserId()];
        
        String empid = [select Id, SAP_EmployeeID__c from User where Id =:UserInfo.getUserId()].SAP_EmployeeID__c;
        String endpointUrl = 'https://castironpoc.w2k.nestle.net/userStatusAndInfo';
        HttpRequest req = new HttpRequest();
        req.setMethod('GET');
        req.setTimeout(60000);
        req.setEndpoint(endpointUrl+'?EmployeeID='+empid+'&sfid='+UserInfo.getUserId());
        
        //send the request
        Http http = new Http();
        System.debug('Callout to Cast Iron : ' + endpointUrl+'?EmployeeID='+empid+'&sfid='+UserInfo.getUserId());
        HttpResponse res = http.send(req);
        
        String httpresult = res.getBody();

        if (res.getStatus() == 'Success') {
            System.debug('******** IBM HTTP LR Test ****** :'+res.getBody());
        } else {
            System.debug('Callout failed: ' + res);
        } 
        
        //remove all old Leave Balances        
        //delete bls;
       **/ 
    }
	
}