PharmaDemo/src/objects/Leave_Request__c.object
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Leave_Type__c</fullName>
        <label>Leave Type</label>
        <picklist>
            <picklistValues>
                <fullName>Vacation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Work Accident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sick Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpaid Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sick Leave (average)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Short_Title__c</fullName>
        <description>Formula field summarizing the request. Useful for mobile display</description>
        <formula>TEXT(DAY(From__c)) &amp; &quot; &quot; &amp;
CASE( MONTH(From__c),
  1, &quot;Jan&quot;,
  2, &quot;Feb&quot;,
  3, &quot;Mar&quot;,
  4, &quot;Apr&quot;,
  5, &quot;May&quot;,
  6, &quot;Jun&quot;,
  7, &quot;Jul&quot;,
  8, &quot;Aug&quot;,
  9, &quot;Sep&quot;,
 10, &quot;Oct&quot;,
 11, &quot;Nov&quot;,
 12, &quot;Dec&quot;,
&quot;—&quot;) &amp; &quot; &quot; &amp;
TEXT(YEAR(From__c))

&amp; &apos; : &apos; 

&amp; TEXT(Leave_Type__c)</formula>
        <label>Short Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>Date</type>
    </fields>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{DD}-{MM}-{YYYY}-{000}</displayFormat>
        <label>Leave Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Purchase_Requisition__c.object
<CustomObject>
    <fields>
        <fullName>Ending_Date__c</fullName>
        <label>Ending Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Resource_Project_Name__c</fullName>
        <inlineHelpText>Please indicate the resource or project</inlineHelpText>
        <label>Resource/Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Starting_Date__c</fullName>
        <label>Starting Date</label>
        <type>Date</type>
    </fields>
    <label>Purchase Requisition</label>
    <nameField>
        <displayFormat>PR-{DD}-{MM}-{YY}-{000}</displayFormat>
        <label>Purchase Requisition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Requisitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/classes/BlackBerryApprovalListController.cls
/*
* Developed by Timba Software Corp. www.timbasoftware.com admin@timbasoftware.com
*/ 

/**
* @author Guillermo Lacordelle
*/ 
public with sharing class BlackBerryApprovalListController
{
	
	private List<ApprovalItemCollection> approvalItemsCollection;
		
	private Id userId = UserInfo.getUserId();
	
	public Boolean noRecordsToShow = false;
	

	
	/**
	* @return whether there isn't an approval request for the user.
	*/
	public Boolean getNoRecordsToShow()
	{
		return noRecordsToShow;
	}
	
	
	/**
	* @return a list of approval items classified by type
	*/
	public List<ApprovalItemCollection> getApprovalItemsCollection()
	{
		if (approvalItemsCollection == null)
		{
			List<ProcessInstanceWorkitem> workItems;
			List<ProcessInstance> processInstances;
			
			workItems = [
				select processInstance.id, createdDate, actor.name, actor.id				
				from ProcessInstanceWorkitem
				where actor.id = :userId
			];
			
			List<Id> processInstancesIds = new List<Id>();
			for (ProcessInstanceWorkitem item : workItems)
			{
				processInstancesIds.add(item.processInstance.id);
			}
			
			processInstances = [
				select
					id,
					targetObject.id,
					targetObject.type,
					targetObject.name,
					(select id, createdDate, actorId from workItems where actorId = :userId)
				from ProcessInstance
				where id in :processInstancesIds and (targetObject.type = 'Leave_Request__c' or targetObject.type = 'Purchase_Requisition__c')
				order by targetObject.type
				//DVP : Modified where clause
			];
			
			//DVP : Create a list of all Leave Requests needing approval
			List<Id> LeaveRequestIds = new List<Id>();
			List<Id> PurchaseIds = new List<Id>();
			for(ProcessInstance pi : processInstances) {
				if (pi.TargetObject.type == 'Leave_Request__c')
				  LeaveRequestIds.add(pi.targetObjectId);
				else
				  PurchaseIds.add(pi.targetObjectId);
			}
			//DVP : Get the leave requests
			Map<Id, Leave_Request__c> leaverequests = new Map<Id,Leave_Request__c>([select Id, Name, From__c, To__c, Leave_Type__c, Short_Title__c, Owner.Name from Leave_Request__c where Id in :LeaveRequestIds]);
			Map<Id, Purchase_Requisition__c> purchases = new Map<Id, Purchase_Requisition__c>([Select Id, Name, Resource_Project_Name__c, Starting_Date__c, Ending_Date__c, Owner.Name From Purchase_Requisition__c Where Id in :PurchaseIds]);
			
			
			approvalItemsCollection = new List<ApprovalItemCollection>();
			String lastType;
			ApprovalItemCollection currentCollection;
			Map<String, Schema.SObjectType> sObjectTypeMap = Schema.getGlobalDescribe();
			for (ProcessInstance instance : processInstances)
			{
				String instanceType = instance.targetObject.type;
				if (instanceType != lastType)
				{
					currentCollection = new ApprovalItemCollection();
					currentCollection.itemsList = new List<ApprovalItem>();
					Schema.SObjectType objType = sObjectTypeMap.get(instanceType);
					currentCollection.itemsPluralLabel = (objType == null ? instanceType : objType.getDescribe().getLabelPlural());
					currentCollection.itemsType = instanceType;
					approvalItemsCollection.add(currentCollection);
					lastType = instanceType;
				}
				ApprovalItem apprItem = new ApprovalItem();
				apprItem.instance = instance;
				apprItem.workItem = instance.workItems[0];
				if (leaverequests.containsKey(instance.targetObject.Id))
				  apprItem.leaverequest = leaverequests.get(instance.targetObject.Id); //DVP
				if (purchases.containsKey(instance.targetObject.Id)) {
				  apprItem.purchase = purchases.get(instance.targetObject.Id);
				  apprItem.isPurchase = true;
				}
				currentCollection.itemsList.add(apprItem);
			}
		}
		
		if(approvalItemsCollection.size() <= 0)
		{
			noRecordsToShow = true;
		} 
		
		
		return approvalItemsCollection;
	}
	
	
	/**
	* Class ApprovalItem
	*/
	class ApprovalItem
	{
		public ProcessInstanceWorkitem workItem { get; set; }
		public ProcessInstance instance { get; set; }
		public SObject target { get; set; }
		public Leave_Request__c leaverequest {get;set;} //DVP
		public Purchase_Requisition__c purchase { get; set; }
		public Boolean isPurchase { get; set; }
		public String relatedTo
		{
			get
			{
				return instance.targetObject.name;	
			}
			set;
		}
		public String dateSubmitted
		{
			get
			{
				return workItem.createdDate.format('MM/dd/yyyy');	
			}
			set;
		}
		public ApprovalItem() {
			isPurchase = false;
		}
	}
	
	
	/**
	* Class ApprovalItemCollection
	*/
	class ApprovalItemCollection
	{
		public List<ApprovalItem> itemsList { get; set; }
		public String itemsType { get; set; }
		public String itemsPluralLabel { get; set; }
	}
		
}