PharmaDemo/src/objects/Leave_Request__c.object
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Leave_Type__c</fullName>
        <label>Leave Type</label>
        <picklist>
            <picklistValues>
                <fullName>Vacation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Work Accident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sick Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpaid Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sick Leave (average)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>Date</type>
    </fields>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{DD}-{MM}-{YYYY}-{000}</displayFormat>
        <label>Leave Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/classes/LeaveRequestDetailController.cls
public with sharing class LeaveRequestDetailController {

	@RemoteAction
	public static String saveLeaveRequest(String id, String leavetype, Date fromdate, Date todate, String notes) {
		
		Leave_Request__c lr;
		//see it this Leave Request Already exists
		try {
			lr = [select Id from Leave_Request__c where id =:id];
		}
		catch(Exception ex) {
			lr = new Leave_Request__c();	
		}
		
		//fill in the new data
		lr.Leave_Type__c = leavetype;
		lr.From__c = fromdate;
		lr.To__c = todate;
		lr.Notes__c = notes;
		
		//and save
		upsert(lr);
		
		return 'Saved';
	}

}