PharmaDemo/src/objects/Leave_Request__c.object
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Leave_Type__c</fullName>
        <label>Leave Type</label>
        <picklist>
            <picklistValues>
                <fullName>Vacation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Work Accident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sick Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpaid Leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sick Leave (average)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>Date</type>
    </fields>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{DD}-{MM}-{YYYY}-{000}</displayFormat>
        <label>Leave Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/classes/BlackBerryApprovalTestUtility.cls
@isTest
/*
* Developed by Timba Software Corp. www.timbasoftware.com admin@timbasoftware.com
*/
 
/**
* Aux class to generate the items needed for code coverage tests.
* @author Bruno Fagundez
*/ 
public with sharing class BlackBerryApprovalTestUtility {
	
	/**
	* Method to generate the enviroment to run tests on empty orgs.
	*/ 
	public static testMethod void genApproval()
	{
		
		/**
		// Insert a dummy Account 
		Account acct = new Account();
		acct.Name = 'Test Method Account';
		insert acct;
		
		// Insert a dummy Contact
		Contact contact = new Contact();
		contact.AccountId = acct.id;
		contact.LastName = 'Test Method Contact';
		insert contact;
		**/
		
		//insert some leave requests
		Leave_Request__c lr = new Leave_Request__c();
		lr.From__c = Date.today();
		lr.To__c = Date.today().addDays(1);
		lr.Leave_Type__c = 'Vacation';
		lr.Notes__c = 'notes';
		
		insert lr;
		
		Leave_Request__c lr2 = new Leave_Request__c();
		lr2.From__c = Date.today();
		lr2.To__c = Date.today().addDays(1);
		lr2.Leave_Type__c = 'Vacation';
		lr2.Notes__c = 'notes';
		
		insert lr2;
		
		// Insert 2 Approval proccesses.
		Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
		req1.setComments('lorem ipsum');
		req1.setObjectId(lr.Id);
		req1.setNextApproverIds(new Id[] {Userinfo.getUserId()});
		
		Approval.ProcessResult result = Approval.process(req1);
		
		Approval.ProcessSubmitRequest req2 = new Approval.ProcessSubmitRequest();
		req2.setComments('lorem ipsum');
		req2.setObjectId(lr2.Id);
		req2.setNextApproverIds(new Id[] {Userinfo.getUserId()});
		
		Approval.ProcessResult result2 = Approval.process(req2);
		
		List<Id> newWorkItemIds = result.getNewWorkitemIds();
		 
		BlackBerryApprovalTestUtil.workitemId = newWorkItemIds[0];
		 
	}
}