PharmaDemo/src/objects/Order_Line_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pack_Size__c</fullName>
        <label>Pack Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_custom__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Stock_Product__c</referenceTo>
        <relationshipLabel>Order Line Details</relationshipLabel>
        <relationshipName>Order_Line_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SKU_Name__c</fullName>
        <label>SKU #</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock_Order__c</fullName>
        <label>Stock Order</label>
        <referenceTo>Stock_Order__c</referenceTo>
        <relationshipLabel>Order Line Details</relationshipLabel>
        <relationshipName>Order_Line_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Line Detail</label>
    <nameField>
        <displayFormat>LINE-{00000}</displayFormat>
        <label>Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/SKU__c.object
<CustomObject>
    <description>Stock Keeping Units</description>
    <fields>
        <fullName>Custom_Product__c</fullName>
        <label>Product</label>
        <referenceTo>Stock_Product__c</referenceTo>
        <relationshipLabel>SKU#</relationshipLabel>
        <relationshipName>SKU_s</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Line_Item_Quantity__c</fullName>
        <description>This is a dummy field used on SKU for inputting the quantity of SKU&apos;s for a particular order Line Item. This is included to allow for easier code update and to avoid having to use a nested class to pass records to the visual force page.</description>
        <label>Order Line Item Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pack_Size__c</fullName>
        <label>Pack Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>SKU</label>
    <nameField>
        <label>SKU Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SKU&apos;s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Stock_Order__c.object
<CustomObject>
    <label>Stock Order</label>
    <nameField>
        <displayFormat>ORDER-{000000}</displayFormat>
        <label>Stock Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Stock_Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Alli</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Niquitin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lactacyd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panadol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zovirax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corega</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oral Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smoking Cessation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Analgesic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coughs and Colds</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Stock Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/classes/ProductExtension.cls
public class ProductExtension {
    
    public Stock_Order__c contextStockOrder;    //The current Stock Order referenced from the VF page
   
   
    public String selectedCategory { get; set; }                               //the currently selected product category
    public String selectedProduct { get; set; }                                //Id of the currently selected product  
    public Boolean isProductCategoryNotNone { get; set; }                      //Tells us if the selected Category is --None--                                           
    public Boolean showSKUPageBlockSection { get; set; }
    public Boolean showSaveMessage { get; set; }
    public String saveMessageTitle { get; set; }
    public String saveMessageDetail { get; set; }                       
    
                                              
    public List<Order_Line_Detail__c> orderDetailsList;
    public List<Stock_Product__c> stockProducts = new List<Stock_Product__c>();                                              
    public List<SelectOption> allProductCategories = new List<SelectOption>(); //Houses all the product categories
    public List<SelectOption> allProducts = new List<SelectOption>();          //Houses all the products
    public List<SKU__c> skuRecordsList = new List<SKU__c>();             //Houses SKU Records for the product in context
    
    
    //mandatory controller extension constructor...
    public ProductExtension (ApexPages.StandardController stdController) {
        this.contextStockOrder = (Stock_Order__c) stdController.getRecord();
        queryForProductCategories();
        showSaveMessage = false;
    }
    
    //This method queries for all the current Stock product Categories...
    public void queryForProductCategories() {

        //Get the Field Token
        Schema.SObjectField sf = Stock_Product__c.Product_Type__c;
        //Call describe on the Field Token
        Schema.DescribeFieldResult sdfr = sf.getDescribe();
       
        //add the defaul sf selectlist value to
        //the SelectOption list...
        allProductCategories.add(new SelectOption('null','--None--'));

        for( Schema.PicklistEntry plentry : sdfr.getPicklistValues())
            allProductCategories.add(new SelectOption(plentry.getValue(),plentry.getLabel()));
    }
    
    //This method querys for all the products associated
    //with the selected category
    public void queryForProducts() {
        //reset the Products for each click of the
        //Product category list...
        if(allProducts.size() > 0)
            allProducts = new List<SelectOption>();
    
        //if the selected category is not '--None--'
        if (selectedCategory != 'null') {
            isProductCategoryNotNone = true;
            
            //add a default selectOption to the allProductsList
            allProducts.add(new SelectOption('null','--None--'));
            
            //Loop through all the products for this category and add to the allProductsList
            for(Stock_Product__c dbstockProduct : [Select Id, Name From Stock_Product__c Where Product_Type__c =:selectedCategory])
                allProducts.add(new SelectOption(dbstockProduct.id,dbstockProduct.Name)); 
                
        }else {
            //Selected category is '--None--'
            isProductCategoryNotNone = false;
        }
        
        showSKUPageBlockSection = false;
    }
    
    //This method will query for all the SKU's associated with
    //the product that is selected from the visualforce page (products list)
    public void queryForSKUs() {
        //each time this method is invoked, we want to 
        //reset the available SKU's for the table
        skuRecordsList = new List<SKU__c>();
        
        if(selectedProduct != 'null') {        
            try {
                /*
                 *  CHANGE SOQL Query to retrieve your SKU fields
                 */
            skuRecordsList = [Select Name, Description__c, Pack_Size__c, Price__c, Order_Line_Item_Quantity__c From SKU__c Where Custom_Product__c =:selectedProduct]; 
                    
            if(skuRecordsList.size() > 0)
                showSKUPageBlockSection = true;
            
            }catch(QueryException qe) {
                System.debug('********* THERE WAS A QUERY ERROR: ' + qe.getMessage());
            }
        }else {
            showSKUPageBlockSection = false;
        }
    }
    
    //This method rolls all the SKU's that have
    //a quantity >= 1 up to the Master Stock Order Detail Line Item
    public PageReference addToOrder() {
        orderDetailsList = new List<Order_Line_Detail__c>();
        
        //Loop through all the SKU records that are in the Table...
        for(SKU__c currentSKURecord : skuRecordsList) {
            //If any of the records have a quantity > 1...
            if(currentSKURecord.Order_Line_Item_Quantity__c >= 1) {
                //Create a new Order_Line_Detail__c record...
                Order_Line_Detail__c newOrderDetailRec = new Order_Line_Detail__c(Stock_Order__c = contextStockOrder.id, 
                                                                                  SKU_Name__c = currentSKURecord.Name,
                                                                                  Product_custom__c = selectedProduct,
                                                                                  Pack_Size__c = currentSKURecord.Pack_Size__c,
                                                                                  Description__c = currentSKURecord.Description__c,
                                                                                  Quantity__c = currentSKURecord.Order_Line_Item_Quantity__c,
                                                                                  Price__c = (currentSKURecord.Order_Line_Item_Quantity__c * currentSKURecord.Price__c));
                //and add to the list to be commited to the database.
                orderDetailsList.add(newOrderDetailRec);
            }
        }
        
        //If there are records to be inserted to the DataBase...
        if(orderDetailsList.size() > 0) {
            try {
                //Perform an upsert.
                upsert(orderDetailsList);
                
                saveMessageTitle = 'SKU\'s successfully saved';
                saveMessageDetail = 'A total of ' + orderDetailsList.size() + ' were added to your order';
            }catch(DMLException dmle) {
                
                saveMessageTitle = 'SKU save error';
                saveMessageDetail = 'There was an error adding the SKU\'s to the order';
                System.debug('****** THERE WAS AN UPSERT ERROR: ' + dmle.getMessage());
            }finally {
                showSaveMessage = true;
            }
        }  

        //Do not want to display pageBlockSection
        //after an order line item is added...
        isProductCategoryNotNone = false;
        
        //clear the SKU list
        skuRecordsList.clear();
        
        //remove the SKU page block section
        showSKUPageBlockSection = false;

        //Do not want to navigate away from the 
        //current visual force page.
        return null;
    }
    
    public PageReference reviewOrder() {
        PageReference orderDetailPage = new PageReference('/' + contextStockOrder.Id);
        orderDetailPage.setRedirect(true);
        return orderDetailPage;
    }
    
    //This method clears the save message on
    //the visual force page.
    public PageReference clearSaveMessage() {
        showSaveMessage = false;
        return null;
    }
    
    /*
     * Define getters & setters
     */
    public List<SelectOption> getAllProductCategories() {
        return allProductCategories;
    }
    
    public List<SelectOption> getAllProducts() {
        return allProducts;
    }

    public List<SKU__c> getSkuRecordsList() {
        return skuRecordsList;
    }
    
    public Boolean getisProductCategoryNotNone() {
        return isProductCategoryNotNone;
    }
    
    public void setAllProductCategories(List<SelectOption> categories) {
        this.allProductCategories = categories;
    }
    
    public void setAllProducts(List<SelectOption> products) {
        this.allProducts = products;
    }
    
    public void setSKURecordsList(List<SKU__c> skusList) {
        this.skuRecordsList = skusList;
    }
}