PharmaDemo/src/objects/Purchase_Requisition__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Cost_Center_Code__c</fullName>
        <label>Cost Center Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <label>Cost Center</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ending_Date__c</fullName>
        <label>Ending Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Starting_Date__c</fullName>
        <label>Starting Date</label>
        <type>Date</type>
    </fields>
    <label>Purchase Requisition</label>
    <nameField>
        <displayFormat>PR-{DD}-{MM}-{YY}-{000}</displayFormat>
        <label>Purchase Requisition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Requisitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/classes/TestPurchases.cls
@isTest
public with sharing class TestPurchases {


	//test purchaseextension
	private static testmethod void testpurchaseextension() {
		
		Purchase_Requisition__c pr = new Purchase_Requisition__c();
		pr.Approval_Status__c = 'Pending';
		pr.Comments__c = 'comments';
		pr.Cost_Center__c = 'z01';
		pr.Cost_Center_Code__c = 'z01';
		pr.Ending_Date__c = Date.today().addDays(10);
		pr.Starting_Date__c = Date.today();
		
		insert pr;
		
		ApexPages.Standardcontroller con = new ApexPages.Standardcontroller(pr);
		PurchaseExtension pe = new PurchaseExtension(con);
		pe.getFormattedEnd();
		pe.getFormattedStart();
		pe.cancel();
		pe.save();
		
		Purchase_Requisition__c pr2 = new Purchase_Requisition__c();
		pr2.Approval_Status__c = 'Pending';
		pr2.Comments__c = 'comments';
		pr2.Cost_Center__c = 'z01';
		pr2.Cost_Center_Code__c = 'z01';
		pr2.Ending_Date__c = Date.today().addDays(10);
		pr2.Starting_Date__c = Date.today();

		
		ApexPages.Standardcontroller con2 = new ApexPages.Standardcontroller(pr2);
		PurchaseExtension pe2 = new PurchaseExtension(con2);		
		pe2.cancel();
		pe2.save();
		pe2.sendToSAP();
		
	}
	
	
	//test purchasesetcontroller
	private static testmethod void testpurchasesetcontroller() {
		Purchase_Requisition__c pr = new Purchase_Requisition__c();
		pr.Approval_Status__c = 'Pending';
		pr.Comments__c = 'comments';
		pr.Cost_Center__c = 'z01';
		pr.Cost_Center_Code__c = 'z01';
		pr.Ending_Date__c = Date.today().addDays(10);
		pr.Starting_Date__c = Date.today();
		
		insert pr;
		
		ApexPages.Standardsetcontroller con = new ApexPages.Standardsetcontroller([select Id from Purchase_Requisition__c limit 20]);
		PurchaseSetController psc = new PurchaseSetController(con);
		psc.getPurchases();
		
	}

}