PharmaDemo/src/objects/Purchase_Requisition__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cost_Center__c</fullName>
        <label>Cost Center</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ending_Date__c</fullName>
        <label>Ending Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Resource_Project_Name__c</fullName>
        <inlineHelpText>Please indicate the resource or project</inlineHelpText>
        <label>Resource/Project Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Starting_Date__c</fullName>
        <label>Starting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vendor</label>
        <referenceTo>Vendor__c</referenceTo>
        <relationshipLabel>Purchase Requisitions</relationshipLabel>
        <relationshipName>Purchase_Requisitions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchase Requisition</label>
    <nameField>
        <displayFormat>PR-{DD}-{MM}-{YY}-{000}</displayFormat>
        <label>Purchase Requisition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Requisitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/objects/Vendor__c.object
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PharmaDemo/src/classes/PurchaseSetController.cls
public class PurchaseSetController
{
  public ApexPages.StandardSetController setCon 
  {
    get 
    {
      if (setCon == null) {
        setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
          [
            Select Resource_Project_Name__c, Starting_Date__c, Ending_Date__c, Cost_Center__c, Vendor__r.Name, Approval_Status__c
            From Purchase_Requisition__c
            Where OwnerId = :UserInfo.getUserId()
          ]
        ));
      }
      return setCon;
    }
    set;
  }
  public String status { get; set; }
  
  public Map<String, List<Purchase_Requisition__c>> getPurchases()
  {
    Map<String, List<Purchase_Requisition__c>> itemMap = new Map<String, List<Purchase_Requisition__c>>();
    for (Purchase_Requisition__c item : (List<Purchase_Requisition__c>)setCon.getRecords()) {
      if (status == 'All' || status == item.Approval_Status__c) {
        if (item.Approval_Status__c == null) item.Approval_Status__c = 'None';
        if (!itemMap.containsKey(item.Approval_Status__c))
          itemMap.put(item.Approval_Status__c, new List<Purchase_Requisition__c>());
        itemMap.get(item.Approval_Status__c).add(item);
      }
    }
    return itemMap;
  }
  
  public PurchaseSetController(ApexPages.StandardSetController c)
  {
    status = ApexPages.currentPage().getParameters().get('status');
    if (status == null) status = 'Draft';
  }
}